// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.21.5
// source: pkg/grpc/userapi.proto

package grpc

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// UserapiClient is the client API for Userapi service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type UserapiClient interface {
	GetUser(ctx context.Context, in *UserRequest, opts ...grpc.CallOption) (*UserReply, error)
}

type userapiClient struct {
	cc grpc.ClientConnInterface
}

func NewUserapiClient(cc grpc.ClientConnInterface) UserapiClient {
	return &userapiClient{cc}
}

func (c *userapiClient) GetUser(ctx context.Context, in *UserRequest, opts ...grpc.CallOption) (*UserReply, error) {
	out := new(UserReply)
	err := c.cc.Invoke(ctx, "/grpc.Userapi/GetUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// UserapiServer is the server API for Userapi service.
// All implementations must embed UnimplementedUserapiServer
// for forward compatibility
type UserapiServer interface {
	GetUser(context.Context, *UserRequest) (*UserReply, error)
	mustEmbedUnimplementedUserapiServer()
}

// UnimplementedUserapiServer must be embedded to have forward compatible implementations.
type UnimplementedUserapiServer struct {
}

func (UnimplementedUserapiServer) GetUser(context.Context, *UserRequest) (*UserReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUser not implemented")
}
func (UnimplementedUserapiServer) mustEmbedUnimplementedUserapiServer() {}

// UnsafeUserapiServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to UserapiServer will
// result in compilation errors.
type UnsafeUserapiServer interface {
	mustEmbedUnimplementedUserapiServer()
}

func RegisterUserapiServer(s grpc.ServiceRegistrar, srv UserapiServer) {
	s.RegisterService(&Userapi_ServiceDesc, srv)
}

func _Userapi_GetUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserapiServer).GetUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc.Userapi/GetUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserapiServer).GetUser(ctx, req.(*UserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Userapi_ServiceDesc is the grpc.ServiceDesc for Userapi service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Userapi_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "grpc.Userapi",
	HandlerType: (*UserapiServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetUser",
			Handler:    _Userapi_GetUser_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pkg/grpc/userapi.proto",
}
