auth:
  enablePostgresUser: false
  # postgresPassword: "StrongPassword"
  username: "userapi"
  password: "userapi"
  database: "userapi"

# The postgres helm chart deployment will be using PVC postgresql-data-claim
primary:
  persistence:
    enabled: true
    existingClaim: "postgresql-pv-claim"