apiVersion: v1
kind: ConfigMap
metadata:
  name: userapi-config
  labels:
    app: userapi
data:
  API_PORT: "8200"
  GRPC_PORT: "8201"
  PG_HOST: postgres
  CASSANDRA_HOST: cassandra
  CASSANDRA_USER: userapi
  CASSANDRA_PASSWORD: userapi
  REDIS_HOST: redis-master
  REDIS_PASSWORD: userapi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: userapi
spec:
  replicas: 3
  selector:
    matchLabels:
      app: userapi
  template:
    metadata:
      labels:
        app: userapi
    spec:
      containers:
        - name: userapi
          image: userapi:latest
          imagePullPolicy: "Never"
          ports:
            - containerPort: 8200
            - containerPort: 8201
          envFrom:
            - configMapRef:
                name: userapi-config
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: userapi
  labels:
    app: userapi
spec:
  type: NodePort
  ports:
   - port: 8200
     nodePort: 32000
     name: api
   - port: 8201
     nodePort: 32001
     name: grpc
  selector:
   app: userapi